from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field


class CorrectionCategory(str, Enum):
    GRAMMAR = "grammar"
    VOCABULARY = "vocabulary"
    PRONUNCIATION = "pronunciation"
    NATURALNESS = "naturalness"


class CorrectionSeverity(str, Enum):
    MINOR = "minor"
    MODERATE = "moderate"
    IMPORTANT = "important"


class CorrectionItem(BaseModel):
    """Structured representation of a detected English mistake."""
    original: str = Field(description="The user's original phrasing that contained an error")
    corrected: str = Field(description="The natural, corrected version of the phrase")
    explanation: str = Field(description="A concise, plain-English explanation of why this is better")
    category: CorrectionCategory = Field(default=CorrectionCategory.GRAMMAR, description="grammar, vocabulary, pronunciation, or naturalness")
    severity: CorrectionSeverity = Field(default=CorrectionSeverity.MODERATE, description="minor, moderate, or important")


class FeedbackResponse(BaseModel):
    """Feedback payload generated by the AI tutor."""
    corrections: List[CorrectionItem] = Field(default_factory=list, description="List of 0-3 genuine corrections")
    top_fix: Optional[str] = Field(default=None, description="The single most important takeaway rule for the user")
    encouragement: str = Field(default="Keep up the good speaking practice!", description="Short encouraging note")
